# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '迷你微博' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'SDAutoLayout'
  pod 'MJRefresh'


  # Pods for 迷你微博

  target '迷你微博Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '迷你微博UITests' do
    # Pods for testing
  end

end
